config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount Ckeditor::Engine => '/ckeditor'
  root 'creatives#index'
  get 'creatives/index'
  resources :posts
end
# root to: "posts#index"

#   resources :posts

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  #This validates presence of title, and makes sure that the length is not more than 140 words
  validates :title, presence: true, length: {maximum: 140}
  #This validates presence of body
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/creatives_controller.rb
class CreativesController < ApplicationController
  layout "creative"

  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :show, :delete]
  before_action :authenticate_admin!, except: [:index, :show]
  # Index action to render all posts
  def index
    @posts = Post.all
  end

  # New action for creating post
  def new
    @post = Post.new
  end

  # Create action saves the post into database
  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Successfully created post!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error creating new post!"
      render :new
    end
  end

  # Edit action retrives the post and renders the edit page
  def edit
  end

  # Update action updates the post with the new information
  def update
    if @post.update_attributes(post_params)
      flash[:notice] = "Successfully updated post!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error updating post!"
      render :edit
    end
  end

  # The show action renders the individual post after retrieving the the id
  def show
  end

  # The destroy action removes the post permanently from the database
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, alert: "Post Deleted!"
  end
  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admins/shared/_links.html.erb
<div class="col-sm-offset-4 col-sm-4 col-xs-12">
  <% if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.omniauthable? %>
    <% resource_class.omniauth_providers.each do |provider| %>
      <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
    <% end %>
  <% end %>
</div>

app/views/creatives/_bg_primary.html.erb
<section class="bg-primary" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading" id="heading-title">Amy will get you to where you want to be.</h2>
                <hr class="light">
                <p class="text-faded">Offal tbh chicharrones swag flexitarian hammock XOXO mixtape ennui. Kombucha hot chicken whatever photo booth raw denim, jianbing flannel messenger bag PBR&B sartorial kitsch. Bespoke meh lumbersexual cornhole butcher, ethical blue bottle everyday carry chambray vexillologist lomo. Meh health goth succulents iPhone food truck, cliche mumblecore direct trade.</p>
                <a href="#services" class="page-scroll btn btn-default btn-xl">Get Started!</a>
            </div>
        </div>
    </div>
</section>

app/views/creatives/_call_to_action.html.erb
<aside class="bg-dark">
    <div class="container text-center">
        <div class="call-to-action">
            <h2 id="call-action">Testimonials</h2>
            <a href="#" class="btn btn-default btn-xl wow tada">Click here to read more</a>
        </div>
    </div>
</aside>

app/views/creatives/_contact.html.erb
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Let's Get In Touch!</h2>
                <hr class="primary">
                <p>Theres no better time than today to turn your body and health around!</p>
            </div>
            <div class="col-lg-4 col-lg-offset-2 text-center">
                <i class="fa fa-phone fa-3x wow bounceIn"></i>
                <p>123-456-6789</p>
            </div>
            <div class="col-lg-4 text-center">
                <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                <p><a href="mailto:your-email@your-domain.com">amy@gettingjacked.com</a></p>
            </div>
        </div>
    </div>
</section>

app/views/creatives/_header.html.erb
<header>
    <div class="header-content">
        <div class="header-content-inner">
            <h1 id="main-title">AMY LYNCH FITNESS</h1>
            <hr id="main-page">
            <!-- <p>To feel your best, you must be your best!</p> -->
            <a href="#about" class="btn btn-primary btn-xl page-scroll">Find Out More</a>
        </div>
    </div>
</header>

app/views/creatives/_navbar.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand page-scroll" href="#">Amy Lynch Fitness</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="page-scroll" href="#about">About</a>
                </li>
                <li>
                    <a class="page-scroll" href="#services">Services</a>
                </li>
                <li>
                    <a class="page-scroll" href="#portfolio">Portfolio</a>
                </li>
                <li>
                    <!-- <a class="page-scroll" href="#">Blog</a> -->
                    <%= link_to "Blog", posts_path %>
                </li>
                <li>
                    <a class="page-scroll" href="#contact">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/creatives/_portfolio.html.erb
<section class="no-padding" id="portfolio">
    <div class="container-fluid">
        <div class="row no-gutter">
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/jacked.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                TRAIN
                            </div>
                            <div class="project-name">
                                This woman is jacked
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/leg_press.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Leg Press
                            </div>
                            <div class="project-name">
                                Come on girl
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/pinch_an_inch.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Pinch an inch?
                            </div>
                            <div class="project-name">
                                Not anymore
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/dude.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Dudes
                            </div>
                            <div class="project-name">
                                She does them too
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/food.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Food
                            </div>
                            <div class="project-name">
                                Its nothing but fuel
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/toned.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                This
                            </div>
                            <div class="project-name">
                                WILL BE YOU
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>

app/views/creatives/_services.html.erb
<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Services</h2>
                <hr class="primary">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-camera-retro wow bounceIn text-primary"></i>
                    <h3>Instagram Models</h3>
                    <p class="text-muted">You'll get more likes than you could have ever dreamed of!</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-cutlery wow bounceIn text-primary" data-wow-delay=".1s"></i>
                    <h3>Meal Plans</h3>
                    <p class="text-muted">Amy will show you how to whip up healthy and tasty dishes!</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-thumbs-up wow bounceIn text-primary" data-wow-delay=".2s"></i>
                    <h3>Feel Great!</h3>
                    <p class="text-muted">It's not easy, but you'll feel and look your best!</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-heart wow bounceIn text-primary" data-wow-delay=".3s"></i>
                    <h3>Get Healthy</h3>
                    <p class="text-muted">Now is the time, you can't put it off any longer you fatass.</p>
                </div>
            </div>
        </div>
    </div>
<a href="#" class="btn btn-primary btn-xl page-scroll" id="service-button">Find Out More</a>
</section>

app/views/creatives/index.html.erb
<%= render 'navbar' %>
<%= render 'header' %>
<%= render 'bg_primary' %>
<%= render 'services' %>
<%= render 'portfolio' %>
<%= render 'call_to_action' %>
<%= render 'contact' %>
<%= render "posts/footer" %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Amy Lynch Fitness</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <% if admin_signed_in? %>
        <!--This block is only visible to signed in admins -->
          <li><%= link_to 'New Post', new_post_path %></li>
          <li><%= link_to 'My Account', edit_admin_registration_path  %></li>
          <li><%= link_to 'Logout', destroy_admin_session_path, :method => :delete %></li>
        <!-- The block ends here -->
        <% else %>
          <li><%= link_to 'Login', new_admin_session_path  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amy Lynch Fitness</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Cabin:600" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Arvo:700" rel="stylesheet">
  </head>

  <body>

    <%= yield %>

  </body>

</html>

app/views/layouts/creative.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Amy Lynch Fitness</title>
  <%= stylesheet_link_tag 'creative/manifest.css', media: 'all' %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'creative/manifest.js' %>
  <%= csrf_meta_tags %>
</head>

<body>

<%= yield %>

</body>
</html>

app/views/posts/_footer.html.erb
<footer id="my-foot">
  <div class="container">
    <p class="text-muted">&copy; Copyright 2017 Amy Lynch Fitness</p>
  </div>
</footer>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :body, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/_navbar.html.erb
<nav id="blog-nav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
             <!-- <a class="navbar-brand page-scroll">Amy Lynch Fitness</a>  -->
             <%= link_to "Amy Lynch Fitness", root_path, :class=> 'navbar-brand page-scroll' %>
          </div>


        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li> <%= link_to "Home", root_path %> </li>
                <li> <%= link_to "About", root_path %> </li>
                <li> <%= link_to "Services", root_path %> </li>
                <li> <%= link_to "Portfolio", root_path %> </li>
                <li> <%= link_to "Contact", root_path %> </li>
                 <% if admin_signed_in? %>
                    <!--This block is only visible to signed in admins -->
                <li><%= link_to 'New Post', new_post_path %></li>
                <li><%= link_to 'My Account', edit_admin_registration_path  %></li>
                <li><%= link_to 'Logout', destroy_admin_session_path, :method => :delete %></li>
                <!-- The block ends here -->
        <% else %>
          <li><%= link_to 'Login', new_admin_session_path  %></li>
        <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render "posts/form" %>

app/views/posts/hold.html.erb
      <% if admin_signed_in? %>
        <%= link_to "Show", post_path(post), class: "btn btn-primary" %>
        <%= link_to "Edit", edit_post_path(post), class: "btn btn-default" %>
        <%= link_to "Delete", post_path(post), class: "btn btn-danger", data: {:confirm => "Are you sure?"}, method: :delete %>
      <% end %>

app/views/posts/index.html.erb
<%= render 'navbar' %>

<body id="all-posts">

<div id="blog-head" class="jumbotron">
  <!-- <h1>Amy's Blog</h1> -->
  <!-- <p>Tips, Tricks, and other Shit</p> -->
</div>

<div class="container">
  <div class="col-sm-10 col-sm-offset-1 col-xs-12 blog-content">
    <% @posts.each do |post| %>
      <div class="col-xs-12">
        <div class="text-center">
          <h2 class="blog-title"><%= post.title %></h2>
          <h6><%= post.created_at.strftime('%b %d, %Y') %></h6>
        </div>

        <div class="blog-text-index">
          <%= truncate(post.body, length: 200, separator: ' ') %>
        </div>

         <div class="text-center">
          <%= link_to "READ MORE", post_path(post), class: "btn btn-default btn-xl show-button", id: "more-button" %>
        </div>

          <div class="tex-center">
          <% if admin_signed_in? %>
          <%= link_to "Edit", edit_post_path(post), class: "btn btn-default admin-button" %>
          <%= link_to "Delete", post_path(post), class: "btn btn-danger admin-button", data: {:confirm => "Are you sure?"}, method: :delete %>
        <% end %>
        </div>
        <hr>
      </div>
    <% end %>
  </div>
</div>

</body>



<%= render 'footer' %>

app/views/posts/new.html.erb
<h2>Create New Post</h2>

<%= render "posts/form" %>

app/views/posts/show.html.erb
<%= render 'navbar' %>

<body id="single-blog-post">
<div class="container">
  <div class="col-sm-11 col-xs-12 blog-content" id="blog-show">

    <h2 class="text-center blog-title"><%= @post.title %></h2>
    <h5 class="text-center blog-text"><%= @post.created_at.strftime('%b %d, %Y') %></h5>
    <div class="blog-text"><%= raw @post.body %></div>

  </div>

</div>
  <div class="show-buttons">
      <%= link_to "All Posts", posts_path , class: "btn btn-default btn-xl show-button" %>
      <%= link_to "Main Page", creatives_index_path , class: 'btn btn-default btn-xl show-button'%>
    </div>
</body>



<%= render 'footer' %>